# Generated by Django 4.1.3 on 2022-11-26 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='seats',
            field=models.IntegerField(),
        ),
    ]
