# Generated by Django 4.1.3 on 2022-11-26 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_carmodel_age_alter_carmodel_seats'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='carmodel',
            table='cars',
        ),
    ]
