# Generated by Django 4.1.3 on 2022-11-30 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_alter_carmodel_age_alter_carmodel_body_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='updated_at',
        ),
    ]
