# Generated by Django 4.1.3 on 2022-12-07 13:39

import django.db.models.deletion
from django.db import migrations, models

import apps.cars.services


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_carmodel_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='photo',
        ),
        migrations.CreateModel(
            name='CarPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to=apps.cars.services.upload_photo)),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='cars.carmodel')),
            ],
            options={
                'db_table': 'cars_photo',
            },
        ),
    ]
