# Generated by Django 4.1.3 on 2022-12-07 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0011_remove_carmodel_photo_carphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carphoto',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='cars.carmodel'),
        ),
        migrations.AlterField(
            model_name='carphoto',
            name='photo',
            field=models.ImageField(blank=True, upload_to='upload_photo'),
        ),
    ]
