# Generated by Django 4.1.3 on 2022-12-07 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0013_remove_carphoto_photo_carphoto_aaa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carphoto',
            old_name='aaa',
            new_name='photo',
        ),
    ]
