# Generated by Django 4.1.3 on 2022-12-07 15:29

from django.db import migrations, models

import apps.cars.services


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0017_remove_carphoto_photo1_carphoto_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carphoto',
            name='photo',
            field=models.ImageField(upload_to=apps.cars.services.upload_photo),
        ),
    ]
