# Generated by Django 4.1.3 on 2022-12-07 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0018_alter_carphoto_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='age',
            field=models.IntegerField(default=10),
        ),
    ]
