# Generated by Django 4.1.3 on 2022-11-30 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0002_parkmodel_name'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='parkmodel',
            table='a_park',
        ),
    ]
