# Generated by Django 4.1.4 on 2022-12-18 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_park', '0006_remove_autoparkmodel_user_usersautoparksmodel_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autoparkmodel',
            options={'ordering': ['id']},
        ),
        migrations.RenameField(
            model_name='autoparkmodel',
            old_name='user',
            new_name='users',
        ),
        migrations.AlterField(
            model_name='autoparkmodel',
            name='name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterModelTable(
            name='autoparkmodel',
            table='auto_parks',
        ),
    ]
