# Generated by Django 4.1.3 on 2022-11-26 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(max_length=4)),
                ('seats', models.IntegerField(max_length=2)),
                ('body_type', models.CharField(max_length=255)),
                ('engine_volume', models.FloatField()),
            ],
        ),
    ]
