# Generated by Django 4.1.3 on 2022-11-30 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_remove_carmodel_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='age',
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='body_type',
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='engine_volume',
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='seats',
        ),
    ]
