# Generated by Django 4.1.3 on 2022-11-30 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_carmodel_age_carmodel_auto_park_carmodel_body_type_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='carmodel',
            table='cars',
        ),
    ]
