# Generated by Django 4.1.3 on 2022-12-07 12:30

from django.db import migrations, models

import apps.cars.services


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_alter_carmodel_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='photo',
            field=models.ImageField(blank=True, upload_to=apps.cars.services.upload_photo),
        ),
    ]
