# Generated by Django 4.1.3 on 2022-12-07 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0012_alter_carphoto_car_alter_carphoto_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carphoto',
            name='photo',
        ),
        migrations.AddField(
            model_name='carphoto',
            name='aaa',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
