# Generated by Django 4.1.3 on 2022-12-07 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0014_rename_aaa_carphoto_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='carphoto',
            name='photo1',
            field=models.ImageField(blank=True, upload_to='upload_photo'),
        ),
    ]
