# Generated by Django 4.1.3 on 2022-12-07 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0015_carphoto_photo1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carphoto',
            name='photo',
        ),
    ]
