# Generated by Django 4.1.4 on 2022-12-14 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0019_alter_carmodel_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='price',
            field=models.FloatField(default=1222, max_length=9),
            preserve_default=False,
        ),
    ]
