# Generated by Django 4.1.4 on 2022-12-18 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0020_carmodel_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='price',
            field=models.FloatField(),
        ),
    ]
