# Generated by Django 4.1.3 on 2022-11-30 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_alter_carmodel_table'),
        ('auto_park', '0003_alter_parkmodel_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='parkModel',
            new_name='AutoParkModel',
        ),
        migrations.AlterModelTable(
            name='autoparkmodel',
            table='auto_park',
        ),
    ]
